ЗАДАНИЯ С API:
1. Количество капсул каждого типа
2. Среднее время между первым и последним запуском
3. Капсулы без информации о запуске
4. Сравнение Dragon 1.0 и Dragon 1.1. Среднее кол-во повторного использования, среднее кол-во посадок

1. Количество капсул каждого типа

In [37]:
import requests
import pandas as pd
import pandasql as ps

with requests.Session() as session:
    response1 = session.get('https://api.spacexdata.com/v3/dragons')
    response2 = session.get('https://api.spacexdata.com/v3/capsules')
    response3 = session.get('https://api.spacexdata.com/v3/history')

In [15]:
data = response2.json()

df = pd.DataFrame(data)

df['capsule_serial'].count()

np.int64(19)

Среднее время между первым и последним запуском

In [28]:
data = response3.json()
df = pd.DataFrame(data)
df

,id,title,event_date_utc,event_date_unix,flight_number,details,links
0,1,Falcon 1 Makes History,2008-09-28T23:15:00Z,1222643700,4.0,Falcon 1 becomes the first privately developed...,"{'reddit': None, 'article': 'http://www.spacex..."
1,2,SpaceX Wins $1.6B CRS Contract,2008-12-23T01:00:00Z,1229994000,NaN,NASA awards SpaceX $1.6B Commercial Resupply S...,"{'reddit': None, 'article': 'https://www.nasas..."
2,3,Falcon 1 Flight 5 Makes History,2009-07-13T03:35:00Z,1247456100,5.0,"Falcon 1 Flight 5 makes history, becoming the ...","{'reddit': None, 'article': 'http://www.spacex..."
3,4,Falcon 9 First Flight,2010-06-04T18:45:00Z,1275677100,6.0,Met 100% of mission objectives on the first fl...,"{'reddit': None, 'article': 'http://www.bbc.co..."
4,5,Dragon Returns From Earth Orbit,2010-12-08T15:43:00Z,1291822980,7.0,"On December 8, 2010, Dragon became the first p...","{'reddit': None, 'article': 'http://www.cnn.co..."
5,6,First Dragon Visit to Space Station,2012-10-08T00:35:00Z,1349656500,9.0,Dragon becomes the first private spacecraft in...,"{'reddit': None, 'article': 'http://thespacere..."
6,7,Grasshopper Completes Half-Mile Flight,2013-10-07T01:00:00Z,1381107600,NaN,The Grasshopper program finished with a 744m f...,"{'reddit': None, 'article': 'http://spacenews...."
7,8,First Flight of Falcon 9 to GTO,2013-12-03T22:41:00Z,1386110460,12.0,Falcon 9 reaches Geosynchronous Transfer Orbit,"{'reddit': None, 'article': 'http://www.newspa..."
8,9,First Stage Landing,2014-04-18T19:25:00Z,1397849100,14.0,Falcon 9 first stage successfully lands in Atl...,"{'reddit': None, 'article': 'https://www.space..."
9,10,Falcon 9 Reusable Test Vehicle Flies 1000M,2014-05-02T01:00:00Z,1398992400,NaN,"Vehicle completes highest leap to date, lands ...","{'reddit': None, 'article': 'http://www.parabo..."
10,11,SpaceX Awarded Commercial Crew Contract,2014-09-16T01:00:00Z,1410829200,NaN,NASA awards $2.6 billion SpaceX contract to fl...,"{'reddit': None, 'article': 'https://www.washi..."
11,12,Drone Ship Landings,2015-01-10T09:47:00Z,1420883220,19.0,SpaceX begins series of first stage landing at...,{'reddit': 'http://www.reddit.com/r/spacex/com...
12,13,Pad Abort Test,2015-05-06T13:00:00Z,1430917200,NaN,"Crew Dragon tests launch abort system, which c...",{'reddit': 'https://www.reddit.com/r/spacex/co...
13,14,First Land Landing,2015-12-22T01:29:00Z,1450747740,25.0,"On December 21, 2015, the Falcon 9 rocket deli...",{'reddit': 'https://www.reddit.com/r/spacex/co...
14,15,Droneship Landing,2016-04-08T20:43:00Z,1460148180,28.0,"On April 8, 2016, the Falcon 9 rocket launched...",{'reddit': 'https://www.reddit.com/r/spacex/co...
15,16,First Reflight,2017-03-30T22:27:00Z,1490912820,38.0,"On March 30, 2017, SpaceX achieved the world's...",{'reddit': 'https://www.reddit.com/r/spacex/co...
16,17,First Dragon Reflight,2017-06-03T21:07:00Z,1496524020,41.0,This Dragon resupply mission represented the f...,{'reddit': 'https://www.reddit.com/r/spacex/co...
17,18,Falcon Heavy Test Flight,2018-02-06T20:45:00Z,1517949900,55.0,"Maiden flight of Falcon Heavy, using two recov...",{'reddit': 'https://www.reddit.com/r/spacex/co...
18,19,First Block 5 Launch,2018-05-11T20:14:00Z,1526069640,61.0,The Bangabandhu Satellite-1 mission served as ...,{'reddit': 'https://www.reddit.com/r/spacex/co...
19,20,First Block 5 Reflight,2018-08-07T05:18:00.000Z,1533619080,67.0,Indonesian comsat intended to replace the agin...,{'reddit': 'https://www.reddit.com/r/spacex/co...

In [35]:
df['new_date'] = pd.to_datetime(df['event_date_utc'], errors='coerce')

min_time = df['new_date'].min()
max_time = df['new_date'].max()

avg_time = (df['new_date'].max() - df['new_date'].min())
avg_time

Timedelta('3511 days 20:59:00')

3. Капсулы без информации о запуске

In [72]:
data = response2.json()

df = pd.DataFrame(data).fillna(0)
df

,capsule_serial,capsule_id,status,original_launch,original_launch_unix,missions,landings,type,details,reuse_count
0,C101,dragon1,retired,2010-12-08T15:43:00.000Z,1.291823e+09,"[{'name': 'COTS 1', 'flight': 7}]",1,Dragon 1.0,Reentered after three weeks in orbit,0
1,C102,dragon1,retired,2012-05-22T07:44:00.000Z,1.335945e+09,"[{'name': 'COTS 2', 'flight': 8}]",1,Dragon 1.0,First Dragon spacecraft,0
2,C103,dragon1,unknown,2012-10-08T00:35:00.000Z,1.349656e+09,"[{'name': 'CRS-1', 'flight': 9}]",1,Dragon 1.0,First of twenty missions flown under the CRS1 ...,0
3,C104,dragon1,unknown,2013-03-01T19:10:00.000Z,1.362165e+09,"[{'name': 'CRS-2', 'flight': 10}]",1,Dragon 1.0,0,0
4,C105,dragon1,unknown,2014-04-18T19:25:00.000Z,1.397849e+09,"[{'name': 'CRS-3', 'flight': 14}]",1,Dragon 1.1,First Dragon v1.1 capsule,0
5,C106,dragon1,active,2014-09-21T05:52:00.000Z,1.411279e+09,"[{'name': 'CRS-4', 'flight': 18}, {'name': 'CR...",3,Dragon 1.1,First Dragon capsule to be reused,2
6,C107,dragon1,unknown,2015-01-10T09:47:00.000Z,1.420883e+09,"[{'name': 'CRS-5', 'flight': 19}]",1,Dragon 1.1,0,0
7,C108,dragon1,active,2015-04-14T20:10:00.000Z,1.429042e+09,"[{'name': 'CRS-6', 'flight': 22}, {'name': 'CR...",3,Dragon 1.1,Second Dragon capsule to be reused,2
8,C109,dragon1,destroyed,2015-06-28T14:21:00.000Z,1.435501e+09,"[{'name': 'CRS-7', 'flight': 24}]",0,Dragon 1.1,Destroyed on impact after F9 launch failure,0
9,C110,dragon1,active,2016-04-08T20:43:00.000Z,1.460148e+09,"[{'name': 'CRS-8', 'flight': 28}, {'name': 'CR...",2,Dragon 1.1,0,1
10,C111,dragon1,active,2016-07-18T04:45:00.000Z,1.468817e+09,"[{'name': 'CRS-9', 'flight': 32}, {'name': 'CR...",2,Dragon 1.1,0,1
11,C112,dragon1,active,2017-02-19T14:39:00.000Z,1.487515e+09,"[{'name': 'CRS-10', 'flight': 36}, {'name': 'C...",3,Dragon 1.1,0,2
12,C113,dragon1,active,2017-08-14T16:31:00.000Z,1.502728e+09,"[{'name': 'CRS-12', 'flight': 45}, {'name': 'C...",2,Dragon 1.1,The last newly manufactured Dragon 1,1
13,C201,dragon2,active,2019-03-02T07:45:00.000Z,1.551513e+09,"[{'name': 'CCtCap Demo Mission 1', 'flight': 76}]",1,Dragon 2.0,Destroyed in a test anomaly at LZ-1 on April 2...,0
14,C205,dragon2,active,2020-01-19T14:00:00.000Z,1.579442e+09,"[{'name': 'Crew Dragon In Flight Abort Test', ...",1,Dragon 2.0,In construction for use in first mission in co...,0
15,C206,dragon2,active,2020-05-30T19:22:00.000Z,1.590867e+09,"[{'name': 'CCtCap Demo Mission 2', 'flight': 94}]",1,Dragon 2.0,"In Hawthorne, CA as of October 11, 2019. Seen ...",0
16,C202,dragon2,active,0,0.000000e+00,[],0,Dragon 2.0,Capsule used to qualify Dragon 2's environment...,0
17,C203,dragon2,active,0,0.000000e+00,[],0,Dragon 2.0,Rumored to be used for Inflight Abort Test aft...,0
18,C204,dragon2,active,0,0.000000e+00,[],0,Dragon 2.0,Currently in construction for use in DM-2,0

In [73]:

unknown = df.query('original_launch == 0')
unknown

,capsule_serial,capsule_id,status,original_launch,original_launch_unix,missions,landings,type,details,reuse_count
16,C202,dragon2,active,0,0.0,[],0,Dragon 2.0,Capsule used to qualify Dragon 2's environment...,0
17,C203,dragon2,active,0,0.0,[],0,Dragon 2.0,Rumored to be used for Inflight Abort Test aft...,0
18,C204,dragon2,active,0,0.0,[],0,Dragon 2.0,Currently in construction for use in DM-2,0

4. Сравнение Dragon 1.0 и Dragon 1.1. Среднее кол-во повторного использования, среднее кол-во посадок

In [ ]:
data = response2.json()

df = pd.DataFrame(data)
df

In [ ]:
dragon_1_0 = df.query('type == "Dragon 1.0"')
dragon_1_0
landings_1_0 = dragon_1_0['landings'].mean()
reuse_1_0 = dragon_1_0['reuse_count'].mean()
# reuse_1_0
# dragon_1_0

,capsule_serial,capsule_id,status,original_launch,original_launch_unix,missions,landings,type,details,reuse_count
0,C101,dragon1,retired,2010-12-08T15:43:00.000Z,1.291823e+09,"[{'name': 'COTS 1', 'flight': 7}]",1,Dragon 1.0,Reentered after three weeks in orbit,0
1,C102,dragon1,retired,2012-05-22T07:44:00.000Z,1.335945e+09,"[{'name': 'COTS 2', 'flight': 8}]",1,Dragon 1.0,First Dragon spacecraft,0
2,C103,dragon1,unknown,2012-10-08T00:35:00.000Z,1.349656e+09,"[{'name': 'CRS-1', 'flight': 9}]",1,Dragon 1.0,First of twenty missions flown under the CRS1 ...,0
3,C104,dragon1,unknown,2013-03-01T19:10:00.000Z,1.362165e+09,"[{'name': 'CRS-2', 'flight': 10}]",1,Dragon 1.0,None,0

In [55]:
dragon_1_1 = df.query('type == "Dragon 1.1"')
# dragon_1_1
landings_1_1 = dragon_1_1['landings'].mean()
landings_1_1
reuse_1_1 = dragon_1_1['reuse_count'].mean()
reuse_1_1

np.float64(1.0)

In [56]:
print(f'Dragon 1.0: Среднее кол-во повторного использования - {reuse_1_0}, среднее кол-во посадок - {landings_1_0}')
print(f'Dragon 1.1: Среднее кол-во повторного использования - {reuse_1_1}, среднее кол-во посадок - {landings_1_1:.2f}')
# 4. Сравнение Dragon 1.0 и Dragon 1.1. Среднее кол-во повторного использования, среднее кол-во посадок

Dragon 1.0: Среднее кол-во повторного использования - 0.0, среднее кол-во посадок - 1.0
Dragon 1.1: Среднее кол-во повторного использования - 1.0, среднее кол-во посадок - 1.89